# Generated by Django 4.1 on 2023-06-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
