# Generated by Django 4.1 on 2023-06-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smc', '0002_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='account_balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
    ]
