# Generated by Django 4.1 on 2023-06-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smc', '0005_alter_menuitem_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday'), ('Everyday', 'Everyday')], default='Everyday', max_length=20),
        ),
    ]
