# Generated by Django 4.1 on 2023-07-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smc', '0007_alter_menuitem_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
    ]
