# Generated by Django 4.1 on 2023-07-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smc', '0008_transaction_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposite', 'Deposite'), ('Purchase', 'Purchase')], max_length=20),
        ),
    ]
