# Generated by Django 4.1 on 2023-07-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smc', '0009_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
    ]
